export default {
  A: 'red',
  B: 'green',
  C: 'blue',
  D: 'yellow',
  E: 'purple',
  F: 'brown',
  G: 'orange',
  H: 'pink',
  I: 'tomato',
  J: 'skyblue',
  K: 'gold',
  L: 'limegreen',
  M: 'aqua',
  N: 'fuchsia',
  O: 'maroon',
  P: 'teal',
  Q: 'olive',
  R: 'beige',
  S: 'crimson',
  T: 'magenta',
  U: 'cyan',
  V: 'dodgerblue',
  W: 'indianred',
  X: 'salmon',
  Y: 'coral',
  Z: 'yellowgreen',
}
